name: Renovate Traefik

on:
  workflow_dispatch:
  schedule:
    - cron: '6 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: x64
    
    - name: Install niet for yaml parsing
      run: pip install -U niet

    - name: Parse url, sub arm and download traefik
      run: |-
        niet resources hardening_manifest.yaml -o resources.json
        sed 's/amd64/arm64/g' resources.json > resources_arm.json
        URL=$(niet url resources_arm.json)
        echo $URL
        curl --silent --output traefik.tar.gz $URL
        git add traefik.tar.gz
        rm resources*

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push
